apiVersion: v1
kind: Pod
metadata:
  name: docker-pod-with-socket-on-master
spec:
  containers:
  - image: orlix/docker:latest
    imagePullPolicy: Always
    name: container-with-socket
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock-volume
  volumes:
  - name: docker-sock-volume
    hostPath:
      # location on host
      path: /var/run/docker.sock
      # this field is optional
      type: File
  nodeSelector:
    node-role.kubernetes.io/master: ''
  hostPID: true