apiVersion: v1  
kind: Pod  
metadata:  
  name: runasnonroot 
spec:  
  containers:  
  - image: orlix/docker:nonroot
    imagePullPolicy: Always
    name: container-with-socket-runasnonroot
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock-volume
  volumes:
  - name: docker-sock-volume
    hostPath:
      # location on host
      path: /var/run/docker.sock
      # this field is optional
      type: File 
  securityContext:  
#    readOnlyRootFilesystem: true  
    runAsNonRoot: true
