apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: no-access-to-master
  namespace: meetup
spec:
  podSelector:
    matchLabels:
      type: docker-no-master
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.43.100/32