apiVersion: v1  
kind: Pod  
metadata:  
  name: worst-pod 
spec:  
  containers:  
  - image: orlix/docker:latest
    imagePullPolicy: Always
    name: container-with-hostpid
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /rootfs
        name: rootfs
  hostPID: true
  volumes:
  - name: rootfs
    hostPath:
      # location on host
      path: /
      # this field is optional
  nodeSelector:
    node-role.kubernetes.io/master: ''
